service: get-games-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - dynamodb:Scan
      Resource: "*"

functions:
  getGames:
    handler: server.handler
    memorySize: 256  # Optimización de memoria
    timeout: 10      # Se aumentó el timeout para evitar fallos
    events:
      - http:
          path: api/games
          method: get
          cors: true
