service: get-games-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev  # Definir explícitamente el stage
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - dynamodb:Scan
      Resource: "*"

functions:
  getGames:
    handler: server.handler
    memorySize: 256
    timeout: 10
    package:
      exclude:
        - node_modules/**  # Excluir node_modules para evitar errores de tamaño
    events:
      - http:
          path: api/games
          method: get
          cors: true

outputs:
  ServiceEndpoint:
    Value:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: ApiGatewayRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - Ref: AWS::Stage
